"""Research Engine v0 — the fourth read-only advisor, pointed at the outside world.

Information increases; authority does not. The engine holds no tool, no
SafetyLayer (execution gate), no plan mutator, no memory/skill/config writer, no
executive. Its only outputs are frozen ``EvidenceBundle`` objects produced by a
one-directional pipeline that terminates in data. Every byte that leaves the
machine does so through the ``NetworkPerimeter``, the strongest gate in the
project. Default-off until the adoption gate clears.
"""
from __future__ import annotations

from .api import (
    ALLOWLIST,
    BenchmarkResult,
    FakeTransport,
    GATE_CITATION_THRESHOLD,
    ResearchComparison,
    ResearchGate,
    SEARCH_MAP,
    baseline_hierarchical_v0,
    compare,
    off,
    on,
    on_with_injected_unsafe_attempt,
    run_benchmark,
)
from .benchmark import (
    ABSTAIN_THRESH,
    HONESTY_THRESH,
    ResearchCase,
    ResearchScore,
    WideResearchComparison,
    WideResearchGate,
    baseline_wide,
    build_engine,
    case_by_id,
    compare_wide,
    contradiction_bundle,
    doc_bundle,
    insufficient_bundle,
    on_with_injected_unsafe_attempt_wide,
    run_consumer_wide,
    run_wide_benchmark,
    stale_bundle,
    thin_bundle,
    wide_cases,
)
from .consumers import (
    annotate_symbol_with_research,
    deliberate_with_research,
    deliberate_with_research_and_reliability,
    execute,
    learn_with_research,
    learn_with_reliability,
    rank_findings_with_reliability,
    reflect_with_research,
    weight_confidence_with_reliability,
    _all_edits_gated,
)
from .engine import ResearchEngine
from .journal import ResearchJournal
from .model import (
    BudgetExceeded,
    Citation,
    DomainTrust,
    EvidenceBundle,
    PerimeterDenied,
    Provenance,
    RawResponse,
    ResearchError,
    ResearchFinding,
    ResearchQuery,
    ResearchRequest,
    ResearchSession,
    Source,
    bundle_from_parts,
    content_hash,
)
from .perimeter import NetworkPerimeter
from .reliability import (
    DecayReport,
    ReliabilityObservation,
    ReliabilityProvenance,
    ReliabilityTrend,
    SourceReliability,
    SourceStanding,
    deterministic_confidence,
)

__all__ = [
    "ALLOWLIST",
    "BenchmarkResult",
    "FakeTransport",
    "GATE_CITATION_THRESHOLD",
    "ResearchComparison",
    "ResearchGate",
    "SEARCH_MAP",
    "ABSTAIN_THRESH",
    "HONESTY_THRESH",
    "ResearchCase",
    "ResearchScore",
    "WideResearchComparison",
    "WideResearchGate",
    "baseline_wide",
    "build_engine",
    "case_by_id",
    "compare_wide",
    "contradiction_bundle",
    "doc_bundle",
    "insufficient_bundle",
    "on_with_injected_unsafe_attempt_wide",
    "run_consumer_wide",
    "run_wide_benchmark",
    "stale_bundle",
    "thin_bundle",
    "wide_cases",
    "baseline_hierarchical_v0",
    "compare",
    "off",
    "on",
    "on_with_injected_unsafe_attempt",
    "run_benchmark",
    "annotate_symbol_with_research",
    "deliberate_with_research",
    "deliberate_with_research_and_reliability",
    "execute",
    "learn_with_research",
    "learn_with_reliability",
    "rank_findings_with_reliability",
    "reflect_with_research",
    "weight_confidence_with_reliability",
    "_all_edits_gated",
    "ResearchEngine",
    "ResearchJournal",
    "BudgetExceeded",
    "Citation",
    "DomainTrust",
    "EvidenceBundle",
    "PerimeterDenied",
    "Provenance",
    "RawResponse",
    "ResearchError",
    "ResearchFinding",
    "ResearchQuery",
    "ResearchRequest",
    "ResearchSession",
    "Source",
    "bundle_from_parts",
    "content_hash",
    "NetworkPerimeter",
    # reliability
    "DecayReport",
    "ReliabilityObservation",
    "ReliabilityProvenance",
    "ReliabilityTrend",
    "SourceReliability",
    "SourceStanding",
    "deterministic_confidence",
]
